apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  # This is the configuration file for Prometheus
  prometheus.yml: |
    global:
      scrape_interval: 15s # Scrape targets every 15 seconds

    scrape_configs:
      # --- JOB 1: Scrape our OTel Collector ---
      - job_name: 'otel-collector'
        static_configs:
          - targets: ['otel-collector:8889'] # The service:port we created

      # --- NEW JOB 2: Scrape Kubernetes's internal state metrics ---
      - job_name: 'kube-state-metrics'
        # This tells Prometheus to auto-discover services in Kubernetes
        kubernetes_sd_configs:
          - role: endpoints
        # This section tells Prometheus HOW to find the right service
        relabel_configs:
        # Keep only services that are in the 'kube-system' namespace
        - source_labels: [__meta_kubernetes_namespace]
          action: keep
          regex: kube-system
        # Keep only the service whose name is 'kube-state-metrics'
        - source_labels: [__meta_kubernetes_service_name]
          action: keep
          regex: kube-state-metrics
        # Use the service's port (which is 8080) for scraping
        - source_labels: [__meta_kubernetes_endpoint_port_name]
          action: keep
          regex: http
---
# These are the permissions Prometheus needs to talk to the
# Kubernetes API to discover other pods and services.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
      - configmaps
    verbs: ["get"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus # Use the permissions we created
      containers:
        - name: prometheus
          image: prom/prometheus:v2.45.0
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.retention.time=12h" # Keep data for 12h to save memory
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: ClusterIP # We don't need this on the public internet
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: prometheus
